const allProducts = {
  alcategories: [
    {
      idcategory: "00001",
      order: "01",
      name: "Electrónica",
      icon: "mdi-electron-framework",
      products: [
        { id: "001",
          name: "Audífonos",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididuntut.",
          reserved: false,
          rank: 4.5,
          price: 11.50,
          loading: false,
          img: "http://127.0.0.1:3000/src/assets/products/headphones.png"
        },
        { id: "002",
          name: "Monitor Curvo Dell",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididuntut.",
          reserved: false,
          rank: 4.0,
          price: 210.10,
          loading: false,
          img: "http://127.0.0.1:3000/src/assets/products/dell_curve_monitor.png" },
        { id: "003",
          name: "Ipad",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididuntut.",
          reserved: false,
          loading: false,
          rank: 4.5,
          price: 670.00,
          img: "http://127.0.0.1:3000/src/assets/products/ipad.png" },
        { id: "004",
          name: "Apple Watch",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididuntut.",
          reserved: false,
          loading: false,
          rank: 5.0,
          price: 56.40,
          img: "http://127.0.0.1:3000/src/assets/products/apple_watch.png" },
        { id: "005",
          name: "MackBook Pro",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididuntut.",
          reserved: false,
          loading: false,
          rank: 3.0,
          price: 2350.00,
          img: "http://127.0.0.1:3000/src/assets/products/mackbook_pro.png" },
        { id: "006",
          name: "USB Mouse",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididuntut.",
          reserved: false,
          loading: false,
          rank: 3.5,
          price: 12.50,
          img: "http://127.0.0.1:3000/src/assets/products/computer_mouse.png" },
      ],
    },
    {
      id: "00002",
      order: "02",
      name: "Electrodomésticos",
      icon: "mdi-home-lightning-bolt-outline",
      products: [
        { id: "006",
          name: "Batidora amasadora",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididuntut.",
          reserved:
          false,
          rank: 4.1,
          price: 45.50,
          loading: false,
          img: "http://127.0.0.1:3000/src/assets/products/batidora_amasadora.png"
        },
        { id: "007",
          name: "Holla arrocera",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididuntut.",
          reserved: false,
          rank: 4.0,
          price: 80.50,
          loading: false,
          img: "http://127.0.0.1:3000/src/assets/products/holla_arrocera.png" },
        { id: "008",
          name: "Tostadora para pan",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididuntut.",
          reserved: false,
          loading: false,
          rank: 4.0,
          price: 52.10,
          img: "http://127.0.0.1:3000/src/assets/products/tostadora_de_pan.png" },
        { id: "009",
          name: "Freidora de aire",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididuntut.",
          reserved: false,
          loading: false,
          rank: 5.0,
          price: 90.55,
          img: "http://127.0.0.1:3000/src/assets/products/freidora_de_aire.png" },
        { id: "010",
          name: "Plancha para pan",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididuntut.",
          reserved: false,
          loading: false,
          rank: 3.0,
          price: 48.00,
          img: "http://127.0.0.1:3000/src/assets/products/plancha_para_pan.png" },
        { id: "011",
          name: "Cafetera eléctrica",
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididuntut.",
          reserved: false,
          loading: false,
          rank: 3.0,
          price: 88.00,
          img: "http://127.0.0.1:3000/src/assets/products/cafetera_electrica.png" },
      ],
    },
  ],
  home: [],
};
export default (data) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (allProducts[data] !== undefined) resolve(allProducts[data]);
      reject("Error data doesn't exist");
    }, 300);
  });
};
